### PR TITLE
Update SecretDecks® Newsletter to Occultish.md

### PR DESCRIPTION
**Pull request by evolayak**
@DanM3rcurius @wlstylr @stephen-rowan Can you please look at the "What is a Distributed Cooperative (DisCO)" section? I changed everything in the newsletter from ACO to DisCO, but I'm not sure if this is clear enough... I started to go down an "explanatory rabbit hole" and had way too much text.

### CODE REVIEW

**Comment by wlstylr** [comment]
@evolayak It reads well from my perspective.  I think it's good to merge.  :)

**Comment by evolayak** [comment]
@DanM3rcurius Please take a final look!

**Comment by DanM3rcurius** [comment]
sorry I overlooked this. But I trust Tylers judgement 🙏🏿

**Comment by evolayak** [comment]
Great!

**Pull request merged**
