### PR TITLE
Update Know-Thyself.md

### PR DESCRIPTION
**Pull request by evolayak**
minor proofread throughout; added link to food of the gods; edit to last sentence; and made "T. Mckenna" not in bold- I thought to keep it like the other authors/sources. It also makes the "read thyself" at the bottom stand out. let me know if you want me to change it back.

### CODE REVIEW

**Review by DanM3rcurius — COMMENTED** [review]
Very good edits! Much appreciated 🙏
I feel as if we should have a consistency when writing "know thy/self". We talked about this yesterday and concluded that "Know Thy Self"  is closer to the meaning of "knowing the self (your own self) in you". So I propose whenever it's not a quote to write "Know Thy Self" and "Read Thy Self" respectively. 
Thoughts @evolayak ?

**Comment by evolayak** [comment]
Yep sounds good to me, so I can go in and change all of the "oneself", etc.?  but would have it as "Know Thyself" :)

**Comment by evolayak** [comment]
My only thought with this is that it could read as repetitive, that's initially why I tried to add some variation. But ultimately, if everyone else agrees to have it as "Know Thyself" throughout, then I'm totally cool with it. :)

**Comment by DanM3rcurius** [comment]
@evolayak Should this PR be deleted?

**Pull request merged**
